           Some Alt-Key P-Edit macros supplied with P-Edit

     To invoke these macros, simply type the indicated letter while holding
down the Alt key.

     To define your own single-key macros, use Macro Def and then
respond with your desired Alt-Key (this must be a letter).

   Alt-D   Delete entire current line including the end-of-line character.

   Alt-O   Open up a blank line above the current line and position
           the cursor at this blank line.

   Alt-T   Transpose the two characters just to the left of the cursor.

   Alt-U   Capitalize (first letter) the word containing the cursor.

   Alt-M   Mark your place at the point of the cursor.

   Alt-F   Find and delete Mark (search forward first).

   Alt-R   Reverse find and delete Mark (search only backward).

