echo off
echo ş       The COMit Menu key is set to use the "/" (FORWARD SLASH)
echo ş       as the default key to bring up the menu system.
echo ş
echo ş       You can change this key by going to the "SETUP" menu
echo ş       after starting COMit and selecting the "F"
echo ş       (F-Keys and Menu Access Key) option.
echo ş       It's the last entry on that page.
echo ş
echo           ÃÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
echo           ³P³Com Port                         ³
echo           ÃÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
echo           ³D³Dialing prefix                   ³
echo           ÃÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
echo           ³I³Initialization string            ³
echo           ÃÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
echo           ³T³Terminal Options and Paths       ³
echo           ÃÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
echo           ³H³Host Options and Paths           ³
echo           ÃÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
echo           ³F³F-Keys and Menu Access Key       ³ ---=== select this option
echo           ÀÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
echo            Press [Esc] to return to prior menu
echo          ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
pause
echo          ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo          ³F1  [
echo          ³F2  [
echo          ³F3  [
echo          ³F4  [
echo          ³F5  [
echo          ³F6  [
echo          ³F7  [
echo          ³F8  [
echo          ³F9  [
echo          ³F10 [
echo          ³[/] -- Menu access key override.  (Normally "/")
echo          ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo ş        Change the above key to a single key of your choice.
echo ş        You can NOT use key combinations such as the "Alt", "Ctrl"
echo ş        or the "F" keys.
echo ş
echo ş        You can use keys A-Z (not recomended)
echo ş        0-9 (again not recomended)
echo ş        and keys ! @ # $ % & ( ) ; ? ~ ` " ] [ { }
echo ş
pause
echo ş        Just remember whatever key you select will bring
echo ş        up the menu when you are online. Pushing that key twice
echo ş        will insert that key in whatever you are typing.
echo ş
echo ş        eg, pushing the "/" (the default) once will bring up
echo ş        the menu, pushing it the second time will remove the
echo ş        menu from the screen and insert the "/" in whatever
echo ş        you are typing. If you remember this you may not need
echo ş        to change from the default.
